sudo: required
services:
 - docker

before_install:
 - docker build -t emmanuelgarciads/docker-react -f Dockerfile.dev .

script:
 - docker run emmanuelgarciads/docker-react npm run test -- --coverage
