sudo: required

language: generic

services:
 - docker

before_install:
 - docker build -t emmanuelgarciads/docker-react -f Dockerfile.dev .

script:
 - docker run emmanuelgarciads/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-1-391361142564"
 bucket_path: "docker-react"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
   secure: "$AWS_SECRET_KEY"
